# Generated by Django 3.2.20 on 2023-09-07 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disposalform', '0005_remove_vendor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
