# Generated by Django 3.2.20 on 2023-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposalform', '0006_vendor_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='ltd_compnay',
            new_name='ltd_company',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='ltd_compnay_name',
            new_name='ltd_company_name',
        ),
        migrations.AlterField(
            model_name='business',
            name='date_bought',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='date_est',
            field=models.DateField(),
        ),
    ]
